-- =============================================================================
-- COFOUNDER DIGEST — single-persona rollup of the agent roster + control loop
-- =============================================================================
-- One row per workspace per synthesis run. Rolls up recent `agent_notifications`
-- (Veena, Isha, Neel, Zara, Dev, Priya, Tara, Sam, Kiran, Maya, Riya, Arjun) AND
-- the workspace's GTM control-loop diagnosis (Measure → Diagnose → Recommend)
-- into ONE "your co-founder was busy" narrative — one voice instead of a dozen
-- separate notification rows, in the spirit of a Mengo-style overnight digest.
--
-- Generated by: server/services/cofounderDigest.js
-- Scheduled by: server/services/cofounderDigestScheduler.js (per-workspace daily tick)
-- Consumed by:  src/components/notifications/CofounderDigestCard.jsx
--               (pinned in NotificationsPanel.jsx AND CommandCenter.jsx)
--
-- Verified in this environment (2026): SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY
-- reachable, `workspaces`/`workspace_members`/`agent_notifications` tables exist
-- with live rows, and Realtime subscription on `agent_notifications` returns
-- SUBSCRIBED. Run this migration in the Supabase SQL Editor, then also enable
-- Realtime for `cofounder_digests`:
--   Database → Replication → Supabase Realtime → cofounder_digests
-- =============================================================================

CREATE TABLE IF NOT EXISTS cofounder_digests (
  id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
  workspace_id            UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  period_start            TIMESTAMPTZ NOT NULL,
  period_end              TIMESTAMPTZ NOT NULL,
  headline                TEXT        NOT NULL,
  narrative               TEXT        NOT NULL,
  highlights              JSONB       NOT NULL DEFAULT '[]',   -- [{ agent, agent_role, text }]
  stats                   JSONB       NOT NULL DEFAULT '{}',   -- { tasks_completed, agents_active, action_items_count }
  control_loop_diagnosis  JSONB,                               -- snapshot of controlLoop.lastDiagnosis folded into narrative
  source_notification_ids UUID[]      NOT NULL DEFAULT '{}',
  read                    BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cofounder_digests_user_created
  ON cofounder_digests (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cofounder_digests_workspace_created
  ON cofounder_digests (workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cofounder_digests_unread
  ON cofounder_digests (user_id, read) WHERE read = FALSE;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE cofounder_digests ENABLE ROW LEVEL SECURITY;

-- Any member of the workspace can read/update (mirrors workspace_members-scoped
-- access used elsewhere in this schema) — not just the resolved user_id owner,
-- since digests are workspace-level, not personal.
CREATE POLICY "cofounder_digests_workspace_members" ON cofounder_digests
  FOR ALL USING (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members WHERE user_id = auth.uid()
    )
  );

-- Service role (used by the Node scheduler) bypasses RLS — no extra policy needed.
